### PR TITLE
Filter listed files

### PR DESCRIPTION
**Pull request by acardona**
Implements #33, adding a text box to filter listed files in the ```FileSystemTree``` by matching text or by regular expression when the first character is a '/'.

### CODE REVIEW

**Comment by acardona** [comment]
Hi @ctrueden, can I merge this, given the new status as 'dev'?

Note this PR includes also the commits in PR #31

**Comment by ctrueden** [comment]
@acardona Yes, please merge whatever you like, if you are confident in the changes. You can file a PR to request review in cases where you want it (knowing it may take longer for people to go over the code). Or in cases where you don't feel a review is warranted, just push non-fast-forward merge commits directly without using a PR.

**Comment by acardona** [comment]
Thanks @ctrueden but do I have permissions? Github isn't showing the merge button.

**Comment by acardona** [comment]
Hi @ctrueden , I can't push to scijava master branch, and I can't see a merge button here. So how do I merge?

**Comment by ctrueden** [comment]
Sorry for the delay in reply, @acardona. You have to accept the invitation by visiting this link: https://github.com/scijava/script-editor/invitations. Then you should have push access as well as the ability to merge PRs.

**Pull request merged**
